const NO_ERROR = "NO_ERROR";
const TRANSACTION_TIMEOUT = "TRANSACTION_TIMEOUT";
const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
const DISPENSER_ERROR = "DISPENSER_ERROR";

const ERRORS = {
  NO_ERROR,
  TRANSACTION_TIMEOUT,
  INTERNAL_SERVER_ERROR,
  DISPENSER_ERROR,
};

const ERROR_MESSAGES = {
  INSUFFICIENT_USER_FUNDS: "Insufficient user funds",
};

module.exports = {
  ERRORS,
  NO_ERROR,
  TRANSACTION_TIMEOUT,
  INTERNAL_SERVER_ERROR,
  DISPENSER_ERROR,
  ERROR_MESSAGES,
};
